apiVersion: v1
kind: Secret
metadata:
  labels:
    io.kompose.service: backend-local-env
  name: local-env-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://palms_user:palms_password@postgres:5432/palms_db
  POSTGRES_DB: palms_db
  POSTGRES_USER: palms_user
  POSTGRES_PASSWORD: palms_password
  MINIO_ROOT_USER: palms_minio
  MINIO_ROOT_PASSWORD: palms_minio_password
  S3_ACCESS_KEY_ID: palms_minio
  S3_SECRET_ACCESS_KEY: palms_minio_password
