apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-local-env
  name: local-env
data:
  ADMIN_APP_URL: http://34.220.189.105:31080/admin/
  APP_ENVIRONMENT: development
  APP_NAME: palms-api
  APP_VERSION: 0.1.0
  EMAIL_ENABLED: "true"
  IMAGE_MAX_UPLOAD_MB: "15"
  LOG_LEVEL: INFO
  PUBLIC_APP_URL: http://34.220.189.105:31080
  REDIS_URL: redis://redis:6379/0
  REPORT_EXECUTION_MODE: rq
  RQ_QUEUE_NAME: reports
  S3_BUCKET_NAME: palms-images
  S3_CREATE_BUCKET: "true"
  S3_ENDPOINT_URL: http://minio:9000
  S3_PUBLIC_BASE_URL: http://34.220.189.105:30900/palms-images
  S3_PUBLIC_READ: "true"
  S3_REGION: us-east-1
  S3_USE_PATH_STYLE: "true"
  SESSION_COOKIE_SECURE: "false"
  SESSION_TIMEOUT_MINUTES: "60"
  SMTP_FROM_EMAIL: no-reply@lifemaker.local
  SMTP_FROM_NAME: Lifemaker Foundation
  SMTP_HOST: mailhog
  SMTP_PASSWORD: ""
  SMTP_PORT: "1025"
  SMTP_USE_TLS: "false"
  SMTP_USERNAME: ""
  STORAGE_PROVIDER: s3
