---
- name: Replace localhost with server IP
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ hostvars[inventory_hostname].k3s_ip  }}:6443'

- name: Create .kube directory
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0700"

- name: Copy kubeconfig
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: "0600"
