#SPDX-License-Identifier: MIT-0
---
# tasks file for python
- name: Install Python packages
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-venv
    state: present
    update_cache: true

- name: Create Python virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /opt/ansible-venv
    creates: /opt/ansible-venv

- name: Install Kubernetes Python client
  ansible.builtin.pip:
    name:
      - kubernetes
      - PyYAML
      - jsonpatch
    virtualenv: /opt/ansible-venv