{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "palms.postgres.name" . }}-data
  labels:
    {{- include "palms.componentLabels" (dict "ctx" . "component" "postgres") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
