{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palms.postgres.name" . }}
  labels:
    {{- include "palms.componentLabels" (dict "ctx" . "component" "postgres") | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "palms.componentSelectorLabels" (dict "ctx" . "component" "postgres") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "palms.componentSelectorLabels" (dict "ctx" . "component" "postgres") | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "palms.secretName" . }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "palms.secretName" . }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "palms.secretName" . }}
                  key: POSTGRES_PASSWORD
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.auth.username }}
                - -d
                - {{ .Values.postgres.auth.database }}
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.auth.username }}
                - -d
                - {{ .Values.postgres.auth.database }}
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          {{- if .Values.postgres.persistence.enabled }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: {{ .Values.postgres.persistence.subPath }}
          {{- end }}
      restartPolicy: Always
      {{- if .Values.postgres.persistence.enabled }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "palms.postgres.name" . }}-data
      {{- end }}
{{- end }}
