{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "palms.redis.name" . }}
  labels:
    {{- include "palms.componentLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "palms.componentSelectorLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
{{- end }}
