apiVersion: v1
kind: Secret
metadata:
  name: {{ include "palms.secretName" . }}
  labels:
    {{- include "palms.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "palms.databaseUrl" . | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  MINIO_ROOT_USER: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.auth.rootPassword | quote }}
  S3_ACCESS_KEY_ID: {{ .Values.minio.auth.rootUser | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.minio.auth.rootPassword | quote }}
