[servers]
p1 ansible_host=34.220.189.105 k3s_ip=172.31.42.88 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
p2 ansible_host=54.202.31.74 k3s_ip=172.31.43.91 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
p3 ansible_host=44.247.72.2 k3s_ip=172.31.39.74 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
